# Generated by Django 5.0.4 on 2024-06-05 15:58

import backend.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(null=True)),
                ('city', models.CharField(max_length=150)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('is_vip', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('rent_type', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('description', models.TextField()),
                ('count_of_rooms', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('year_of_construction', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2024)])),
                ('max_floor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(38)])),
                ('floor', models.IntegerField(validators=[django.core.validators.MaxValueValidator(38)])),
                ('height', models.IntegerField()),
                ('apartment_area', models.IntegerField()),
                ('kitchen_area', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('balcony', models.CharField(max_length=255)),
                ('internet', models.CharField(max_length=255)),
                ('bathroom', models.CharField(max_length=255)),
                ('parking', models.CharField(max_length=255)),
                ('furnished_type', models.CharField(max_length=255)),
                ('floor', models.CharField(max_length=255)),
                ('apartment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='backend.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=backend.models.apartment_image_upload_path)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.apartment')),
            ],
        ),
    ]
