# Generated by Django 5.0.4 on 2024-05-16 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='about',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.about'),
        ),
    ]
