# Generated by Django 5.0.4 on 2024-05-24 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='about',
        ),
        migrations.AddField(
            model_name='about',
            name='apartment',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='backend.apartment'),
            preserve_default=False,
        ),
    ]
