# Generated by Django 5.0.4 on 2024-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_apartment_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='latitude',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='longitude',
            field=models.IntegerField(null=True),
        ),
    ]
