# Generated by Django 5.0.4 on 2024-05-29 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_apartment_latitude_alter_apartment_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='location',
        ),
        migrations.AddField(
            model_name='apartment',
            name='house_number',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
