# Generated by Django 5.0.4 on 2024-06-02 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rent_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
