# Generated by Django 5.0.4 on 2024-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_apartment_rent_type_apartment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house_number',
            field=models.CharField(max_length=100),
        ),
    ]
