# Generated by Django 5.0.4 on 2024-06-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_alter_apartment_house_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='door',
        ),
        migrations.RemoveField(
            model_name='about',
            name='phone_status',
        ),
    ]
